jsf:
  primefaces:
    theme: aristo
    font-awesome: true
    push-server-url:

server:
  port: 9090
  servlet:
    context-path: /crawler

spring:
  security:
    user:
      name: user
      password: 123
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:32769/crawler
    username: crawler
    password: crawler
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

