crawler:
  core-pool-size: 1
  max-pool-size: 1
  queue-capacity: 25
  quantity: 1
  max-connections-per-host: 1
  max-total-connections: 10
  connection-timeout: 20000
  socket-timeout: 5000

jsf:
  primefaces:
    theme: aristo
    font-awesome: true

server:
  port: 9090
  servlet:
    context-path: /crawler
  tomcat:
    max-threads: 5

spring:
  security:
    user:
      name: user
      password: 123
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:32771/crawler
    username: crawler
    password: crawler
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
